master:
  image: innfactory/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h master
  hostname: master
  environment:
    MASTER: spark://master:7077
    SPARK_CONF_DIR: /conf
    SPARK_PUBLIC_DNS: localhost
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8080:8080
  volumes:
    - ./conf/master:/conf
    - ./data:/tmp/data

worker:
  image: innfactory/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 4g
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 4041:4040
    - 8081:8081
  volumes:
    - ./conf/worker:/conf
    - ./data:/tmp/data

worker2:
  image: innfactory/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker2
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 4g
    SPARK_WORKER_PORT: 8882
    SPARK_WORKER_WEBUI_PORT: 8082
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 7022
    - 7023
    - 7024
    - 7025
    - 7026
    - 8882
  ports:
    - 4042:4040
    - 8082:8082
  volumes:
    - ./conf/worker2:/conf
    - ./data:/tmp/data

worker3:
  image: innfactory/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
  hostname: worker3
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 4g
    SPARK_WORKER_PORT: 8882
    SPARK_WORKER_WEBUI_PORT: 8082
    SPARK_PUBLIC_DNS: localhost
  links:
    - master
  expose:
    - 7032
    - 7033
    - 7034
    - 7035
    - 7036
    - 8883
  ports:
    - 4043:4040
    - 8083:8083
  volumes:
    - ./conf/worker3:/conf
    - ./data:/tmp/data
